### PR TITLE
Add dependency on boxen

### PR DESCRIPTION
**Pull request by marado**
Closes: #16

### CODE REVIEW

**Comment by egoist** [comment]
not in the right order and needs version number

**Comment by marado** [comment]
Is there any specific minimum version of boxen testen needs?

**Comment by egoist** [comment]
no you can simply `npm i boxen -S`

**Comment by marado** [comment]
Actually, taking into account this:
https://github.com/egoist/testen/commit/77bbe14c7a55cd690c618888810b33760886ad9d
... Why is boxen being required at all?

**Comment by egoist** [comment]
Ah forgot about this, not used anywhere, should remove the require call instead

// ps. clicked wrong button

**Comment by egoist** [comment]
Fixed.

**Pull request closed without merging**
